export * from './types'
export { demoProjects } from './data/demoData'
export { useContentCalendar } from './composables/useContentCalendar'
export { default as ContentCalendarPage } from './components/ContentCalendarPage.vue'
export { default as TrendChip } from './components/TrendChip.vue'
export { default as TrendCard } from './components/TrendCard.vue'
export { default as TrendsSection } from './components/TrendsSection.vue'
