export { useDemoMode } from './composables/useDemoMode'
export { useDemoGuard } from './composables/useDemoGuard'
export { default as DemoIndicator } from './components/DemoIndicator.vue'
export { default as DemoAuthModal } from './components/DemoAuthModal.vue'
export * from './types'
